from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

from .model import Catalog, CatalogEntry, MapPoint, Quest


ALLIANCE_RACE_MASK = 1 | 4 | 8 | 64 | 1024
VISIBLE_EXCLUSION_CODES = {
    "below_starting_state",
    "event",
    "future_phase",
    "monthly",
    "other_class",
    "other_race",
    "profession",
    "recurring",
    "repeatable",
    "starting_state",
    "unreachable_dependency",
}
RECURRING_KINDS = {
    "daily",
    "monthly",
    "repeatable",
    "seasonal_or_event",
    "weekly",
}

# Questie uses negative quest-sort IDs for professions, while the runtime API
# reports the corresponding skill-line IDs. Some TBC rows provide both values;
# others only carry the sort, so keep the relationship explicit here.
PROFESSION_SORT_SKILLS = {
    -24: (182, "Herbalism"),
    -101: (356, "Fishing"),
    -121: (164, "Blacksmithing"),
    -181: (171, "Alchemy"),
    -182: (165, "Leatherworking"),
    -201: (202, "Engineering"),
    -264: (197, "Tailoring"),
    -304: (185, "Cooking"),
    -324: (129, "First Aid"),
    -371: (773, "Inscription"),
    -373: (755, "Jewelcrafting"),
    -377: (794, "Archaeology"),
}


def write_runtime_manifests(catalog: Catalog, project_root: Path) -> list[Path]:
    """Emit the compact, character-neutral data used by the standalone addon.

    Questie's database remains a build input. The addon receives only the facts
    needed for eligibility, completion, routing, and navigation.
    """
    data_root = project_root / "Data"
    data_root.mkdir(parents=True, exist_ok=True)

    visible = {
        quest_id: entry
        for quest_id, entry in catalog.entries.items()
        if _is_visible_to_an_alliance_character(entry)
    }
    zone_counts: dict[int, int] = defaultdict(int)
    quest_rows: list[str] = []
    for quest_id in sorted(visible):
        entry = visible[quest_id]
        record = _quest_record(entry, catalog)
        zone_id = int(record["canonicalZone"])
        zone_counts[zone_id] += 1
        quest_rows.append(f"  [{quest_id}] = {_lua(record)},")

    phase = catalog.phase_profile
    quest_manifest = "\n".join(
        [
            "-- Generated by mads-loremaster. Do not edit by hand.",
            "MadsTBC = MadsTBC or {}",
            "MadsTBC.Manifest = {",
            "  schemaVersion = 1,",
            f"  sourceRevision = {_lua(catalog.source_revision or catalog.source_path)},",
            f"  phase = {_lua({'id': phase.get('id'), 'number': phase.get('phase'), 'name': phase.get('name')})},",
            f"  allianceRaceMask = {ALLIANCE_RACE_MASK},",
            "  quests = {",
            *quest_rows,
            "  },",
            "}",
            "",
        ]
    )
    quest_path = data_root / "QuestManifest.lua"
    quest_path.write_text(quest_manifest, encoding="utf-8")

    zones = []
    for zone_id, count in sorted(zone_counts.items(), key=lambda item: (catalog.zones.get(item[0], ""), item[0])):
        zones.append(
            f"  [{zone_id}] = {_lua({'id': zone_id, 'name': catalog.zones.get(zone_id, f'Zone {zone_id}'), 'questCount': count})},"
        )
    zone_path = data_root / "ZoneManifest.lua"
    zone_path.write_text(
        "\n".join(
            [
                "-- Generated by mads-loremaster. Do not edit by hand.",
                "MadsTBC = MadsTBC or {}",
                "MadsTBC.Zones = {",
                *zones,
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return [quest_path, zone_path]


def _is_visible_to_an_alliance_character(entry: CatalogEntry) -> bool:
    quest = entry.quest
    if quest.content_era != "pre_cataclysm":
        return False
    races = int(quest.get("required_races", 0))
    if races and not races & ALLIANCE_RACE_MASK:
        return False
    if entry.status.startswith("covered") or entry.status in {"baseline_completed", "unavailable"}:
        return True
    return entry.reason_code in VISIBLE_EXCLUSION_CODES


def _quest_record(entry: CatalogEntry, catalog: Catalog) -> dict[str, Any]:
    quest = entry.quest
    kinds = set(entry.conditional_categories)
    quest_sort = int(quest.get("zone_or_sort", 0))
    canonical_zone, zone_name = _canonical_zone(quest, catalog)
    required_skill = _pair_or_none(quest.get("required_skill"))
    profession = PROFESSION_SORT_SKILLS.get(quest_sort)
    if required_skill is None and profession:
        required_skill = [profession[0], 1]
    category = "profession" if required_skill or profession else (entry.category or _category_from_kinds(kinds))
    recurrence = "permanent"
    for candidate in ("daily", "weekly", "monthly", "seasonal_or_event", "repeatable"):
        if candidate in kinds:
            recurrence = candidate
            break
    return {
        "id": quest.id,
        "name": quest.name,
        "questSort": quest_sort,
        "canonicalZone": canonical_zone,
        "zoneName": zone_name,
        "requiredLevel": int(quest.get("required_level", 0)),
        "questLevel": int(quest.get("quest_level", 0)),
        "maximumLevel": _integer_or_none(quest.get("required_max_level")),
        "requiredRaces": int(quest.get("required_races", 0)),
        "requiredClasses": int(quest.get("required_classes", 0)),
        "requiredSkill": required_skill,
        "professionName": profession[1] if profession else None,
        "requiredSpell": _integer_or_none(quest.get("required_spell")),
        "requiredSpecialization": _integer_or_none(quest.get("required_specialization")),
        "requiredRanks": quest.get("required_ranks"),
        "requiredMinRep": _pair_or_none(quest.get("required_min_rep")),
        "requiredMaxRep": _pair_or_none(quest.get("required_max_rep")),
        "prerequisitesAll": list(quest.prerequisites_all),
        "prerequisitesAny": list(quest.prerequisites_any),
        "parentQuest": _integer_or_none(quest.get("parent_quest")),
        "enabledBy": _integer_or_none(quest.get("available_starting_with")),
        "disabledBy": _integer_or_none(quest.get("disabled_by_quest")),
        "breadcrumbFor": _integer_or_none(quest.get("breadcrumb_for_quest_id")),
        "exclusiveTo": list(quest.exclusive_to),
        "category": category,
        "geographic": canonical_zone > 0 and category not in {"dungeon", "raid", "pvp"},
        "kinds": sorted(kinds),
        "recurrence": recurrence,
        "permanent": not bool(kinds & RECURRING_KINDS),
        "eventOnly": "seasonal_or_event" in kinds,
        "phaseStatus": "future" if entry.reason_code == "future_phase" else "current",
        "availablePhase": entry.available_phase,
        "routeBranch": entry.branch,
        "routeOrder": entry.order,
        "sourceStatus": entry.status,
        "sourceReason": entry.reason,
        "sourceReasonCode": entry.reason_code,
        "starter": _source_record(quest, "starter"),
        "finisher": _source_record(quest, "finisher"),
        "objective": _source_record(quest, "objective"),
    }


def _canonical_zone(quest: Quest, catalog: Catalog) -> tuple[int, str]:
    """Return a geographic zone, not a negative profession/class/event sort."""
    quest_sort = int(quest.get("zone_or_sort", 0))
    if quest_sort > 0:
        return quest_sort, catalog.zones.get(quest_sort, f"Zone {quest_sort}")
    for sources in (quest.starter_sources, quest.finisher_sources, quest.objective_sources):
        for source in sources:
            point = _first_point(source.locations)
            if point and point.map_id > 0:
                name = point.map_name or catalog.zones.get(point.map_id, f"Zone {point.map_id}")
                return point.map_id, name
    return quest_sort, catalog.zones.get(quest_sort, f"Zone {quest_sort}")


def _category_from_kinds(kinds: set[str]) -> str:
    for category in ("raid", "dungeon", "pvp", "reputation", "hunter", "world"):
        if category in kinds:
            return category
    return "world"


def _source_record(quest: Quest, kind: str) -> dict[str, Any] | None:
    sources = {
        "starter": quest.starter_sources,
        "finisher": quest.finisher_sources,
        "objective": quest.objective_sources,
    }[kind]
    for source in sources:
        if not source.name and not source.locations:
            continue
        point = _first_point(source.locations)
        return {
            "kind": source.kind,
            "id": source.id,
            "name": source.name,
            "point": {
                "areaId": point.map_id,
                "mapName": point.map_name,
                "x": point.x,
                "y": point.y,
            } if point else None,
        }
    return None


def _first_point(points: tuple[MapPoint, ...]) -> MapPoint | None:
    return points[0] if points else None


def _integer_or_none(value: Any) -> int | None:
    return int(value) if isinstance(value, (int, float)) else None


def _pair_or_none(value: Any) -> list[int] | None:
    if not isinstance(value, list) or len(value) < 2:
        return None
    if not isinstance(value[0], (int, float)) or not isinstance(value[1], (int, float)):
        return None
    return [int(value[0]), int(value[1])]


def _lua(value: Any) -> str:
    if value is None:
        return "nil"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    if isinstance(value, (list, tuple)):
        return "{" + ",".join(_lua(item) for item in value) + "}"
    if isinstance(value, dict):
        fields = []
        for key, item in value.items():
            if item is None:
                continue
            fields.append(f"{key}={_lua(item)}")
        return "{" + ",".join(fields) + "}"
    raise TypeError(f"cannot serialize {type(value).__name__} to Lua")
